### ISSUE TITLE
Find command followed by delete will fail

### ISSUE THREAD

**Issue by rayray39** [AY2425S1-CS2103-F10-2/tp#151]
Performing a find command will create a subset of the entire address book and a subsequent delete command will fail if the index provided is larger than than the number of contacts returned by the find command. 

Say the original address book contact list has 10 people in it, performing a ```find n/ Tan``` returns back 3 people. A follow up delete command ```delete num``` where num is any number greater than 3, will result in the error message 'The person index provided is invalid'. The delete should work since there are 10 people in the address book. The find command seems to create a list with only 3 people in it and thus not allowing a delete to work.

**Comment by AbdulrahmanAlRammah** [comment]
I thought this behavior is intended. The delete refers to the filtered list. If you do delete it deletes the first find result, delete 2 second find result and so on. You can see user guide delete examples.

**Comment by rayray39** [comment]
but shouldnt the user be allowed to delete anybody he wants? and not just on the contacts returned by find? @AbdulrahmanAlRammah

**Comment by AbdulrahmanAlRammah** [comment]
Yes the user can still delete anyone. They just call list and then delete. Practicality wise this makes much more sense and is more useful. A user can find the person they want and delete them. There is no reason a person would memorize the index they want to delete then call find then call the delete. If you use find it makes sense that the commands afterwards are based on the find results.

**Comment by rayray39** [comment]
ok, then you can help to delete this issue then. i got no permissions to delete issues
