### ISSUE TITLE
Edit command causes the contact list to refresh

### ISSUE THREAD

**Issue by Andrew22Teoh** [AY2425S1-CS2103-F10-2/tp#162]
If you execute a `find` command, followed by `edit 1 ...`, this appears to execute a `list` command automatically afterwards, making it harder to view the edited contact and identify where they are. I'm not sure if this is intended, but it seems to make the user experience less smooth.

**Comment by AbdulrahmanAlRammah** [comment]
All you need to do is go tp editcommand execute and delete the line before the return statement that is the line that refreshes the list.
