### ISSUE TITLE
Tags are restricted to alphanumeric characters, so they cannot contain hyphens

### ISSUE THREAD

**Issue by Andrew22Teoh** [AY2425S1-CS2103-F10-2/tp#163]
I'm not sure what this falls under, but we can discuss whether this is something we can leave intact and update the UG for, or if we want to change how it is currently implemented.

This is the case for both the add and the edit command

**Comment by Andrew22Teoh** [comment]
To be updated in UG as a field restriction

**Comment by matchastack** [comment]
On second thought, I think this is important given our target user. Maybe not so much `"-"` but also spaces `" "`.

Related to issue #169, a reasonable tag would be `low income` and `ex-convict`. `low income` may be replaced by `low-income` if space poses a problem in implementation or vice versa for `ex-convict` --> `ex convict` but in any case, 2 or more word tag needs to be allowed.

**Comment by Andrew22Teoh** [comment]
I'll try doing the naive implementation of that and see if it poses any problems with multiple tags parsing!
