### ISSUE TITLE
[PE-D][Tester B] Command parameter constraints not clear in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F10-2/tp#226]
The constraints for command parameters are separated from the commands in the UG.
Consider putting them in the same section for easier reference.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: reginateh/ped#1

**Comment by Andrew22Teoh** [comment]
Purely a suggestion, related to other bugs.

Good bug??

**Comment by Andrew22Teoh** [comment]
Add a hyperlink under add feature description that brings users to Contact Field Requirements instantly if they want to
