### ISSUE TITLE
[PE-D][Tester A] User Guide Missing Date Format Specification for DATE_OF_LAST_VISIT Field

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F10-2/tp#230]
The user guide does not provide information on the required format for the DATE_OF_LAST_VISIT field in the add command section. This lack of documentation may lead to user errors when attempting to add a person with an invalid date format.

**Steps to Reproduce:** 
1. Open the application and refer to the user guide for instructions on adding a person.

2. Attempt to add a person with the DATE_OF_LAST_VISIT field in a format other than DD-MM-YYYY (e.g., MM/DD/YYYY or YYYY-MM-DD).

3. Attempt to add a person with a future date in the DATE_OF_LAST_VISIT field.

![Screenshot 2024-11-08 at 4.32.07 PM.png](https://raw.githubusercontent.com/mattisongjj/ped/main/files/f5efc638-cf57-4c24-adf5-1862c80e35e4.png)

**Expected Result:** 
The user guide should specify that the DATE_OF_LAST_VISIT field must be in DD-MM-YYYY format and no later than the current date within the add command section or provide a link to the contact field requirements section of the documentation

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: mattisongjj/ped#4

**Comment by Andrew22Teoh** [comment]
<img width="833" alt="image" src="https://github.com/user-attachments/assets/1672283c-2b9c-4560-adc5-e71e24f2eed0">

Tester is trying to call a lack of repetition a bug

**Comment by Andrew22Teoh** [comment]
Will be handled by putting contact field requirements upstream of commands
