### ISSUE TITLE
[PE-D][Tester B] Unclear error message for `list`

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F10-2/tp#233]
If I don't follow the command format for `list`, the error message is as follow:
![image.png](https://raw.githubusercontent.com/reginateh/ped/main/files/f5bd5a1b-0a87-4292-82d8-9b7632df6736.png)
It would be better to display the command format for `list`.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: reginateh/ped#3

**Comment by Andrew22Teoh** [comment]
Duplicate of other
