### ISSUE TITLE
[PE-D][Tester A] Misleading Success Message for clear Command on an Empty Address Book

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F10-2/tp#245]
When running the clear command on an empty address book, the application displays the message "Address book has been cleared!" even though no action was taken. This success message may mislead users into thinking there were entries to clear, causing confusion.

**Steps to Reproduce:** 
1. Open the application with an empty address book (no contacts present).

2. Run the clear command.

3. Observe the message displayed.

**Expected Result:** 
The application should display a message indicating that no action was needed, such as "Address book is already empty."

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: mattisongjj/ped#10

**Comment by AbdulrahmanAlRammah** [comment]
This is a niche case that it is out of scope. User can view the list at all times and should be aware of it. Whether there was or wasn't something is irrelevant as the user wanted to clear all entries, the result is the same and informing users is not in the scope of our design. This could be added, but is very minor quality of life fix.
