### ISSUE TITLE
[PE-D][Tester B] `find` empty argument not handled

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F10-2/tp#248]
Currently, it is ok to type an empty argument like:

![image.png](https://raw.githubusercontent.com/reginateh/ped/main/files/23814efd-7b1a-4a92-8e0a-6d0ce6a8749f.png)

Might want to consider blocking this by error messages?

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: reginateh/ped#6

**Comment by AbdulrahmanAlRammah** [comment]
The behaviour is a little inconsistent. Usually find p/, a/ etc. brings up the people who have an address, phone, etc. However, this doesn't work for date of last visit (you get an error message). Should we just list this as out of scope?
