### ISSUE TITLE
[PE-D][Tester C] Valid Email addresses may not be accepted in the App's `email` field

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F10-2/tp#261]
In reality, emails can actually also contain `%` in `localPart`, and `-.` characters in `domain` ([src](https://www.designsystem.tech.gov.sg/patterns/email-address#:~:text=Email%20Address-,Email%20Address,-Use%20this%20pattern))

![image.png](https://raw.githubusercontent.com/superb-sushi/ped/main/files/8fb9bdde-6143-4285-b03d-2a6f03fa0681.png)

The app doesn't accept emails with "%" in `localPart`.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: superb-sushi/ped#8

**Comment by rayray39** [comment]
in my opinion we can just restrict the user to use only alphanumerals
