### ISSUE TITLE
[PE-D][Tester D] Invalid Index Deletion Handling

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F10-2/tp#274]
![{2D0DB750-F33A-4E3F-A150-E4E9DA3BCBDA}.png](https://raw.githubusercontent.com/tansanchian/ped/main/files/9f182c29-2c35-4f34-b427-c049840189c4.png)

![{9AA4C7EB-0A2F-41E8-815F-2791AFED336D}.png](https://raw.githubusercontent.com/tansanchian/ped/main/files/3bf36ea1-ca87-4336-89c9-90b50a0f9ccb.png)

When I try deleting multiple contacts, by mixing up valid indices and invalid indices will not lead to any error. The invalid index will be ignored.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: tansanchian/ped#13

**Comment by Rachael-Chan** [comment]
I dont think this is needed as the command works as intended and testing from developers guide has mentioned that this is the expected result.
<img width="949" alt="Screenshot 2024-11-09 at 20 50 02" src="https://github.com/user-attachments/assets/86d13659-4546-4225-baa9-4c2a5625bbb9">
As shown in point 4 of the screenshot.
