### ISSUE TITLE
[PE-D][Tester C] Error message lacks specificity - `list`

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F10-2/tp#286]
To replicate:
1. `list 1`

![image.png](https://raw.githubusercontent.com/superb-sushi/ped/main/files/87a471d5-ef36-4cca-81c5-dfb04fd61a51.png)
Error message does not specify if the invalid command is due to formatting errors, or because the input is actually invalid.

Suggestion to make error message more specific by informing users that `list` does not accept any parameters.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: superb-sushi/ped#16

**Comment by AbdulrahmanAlRammah** [comment]
Handled by #308 . There was a similar issue.
