### ISSUE TITLE
[PE-D][Tester E] Spelling error for "existing"

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F10-2/tp#288]
![Screenshot 2024-11-08 at 8.03.01 PM.png](https://raw.githubusercontent.com/yu-sutong/ped/main/files/5617b984-773a-44c9-a77e-717035c18142.png)
Mispelt as "existng"

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: yu-sutong/ped#11

**Comment by AbdulrahmanAlRammah** [comment]
closes with #308
