### ISSUE TITLE
[PE-D][Tester D] Inconsistency in Indexing

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F10-2/tp#297]
![{2E02F1C8-C45E-4C27-A0F2-FC6BA9836F46}.png](https://raw.githubusercontent.com/tansanchian/ped/main/files/dc37a4df-4fd2-4e2c-a7c0-06e9adac5ef4.png)

The indexing format is inconsistent when the window is resized to be narrower.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: tansanchian/ped#17

**Comment by matchastack** [comment]
This is **consistent**. User might have assumed it was meant to be *first-row-aligned* but it is **intended** to be *middle-aligned*. 

![image](https://github.com/user-attachments/assets/b294cbb7-a623-4bb8-9a0f-35c23b4716c6)
Even if valid, at best a feature flaw not a functionality bug. does not affect the use of index in anyway.
