### ISSUE TITLE
[PE-D][Tester E] The commands summary seem to be arranged in random.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F10-2/tp#303]
![Screenshot 2024-11-08 at 8.55.35 PM.png](https://raw.githubusercontent.com/yu-sutong/ped/main/files/c76f6211-c6fe-467f-8366-1d618a8f852b.png)
Small nitpick.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: yu-sutong/ped#23

**Comment by matchastack** [comment]
The table header is "command summary". At no point in the document does it suggest any ordering heuristic. This is a personal, specific user expectation/assumption.
